//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KornilovaVarvara420Shop.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderTraсking
    {
        public int IDTracking { get; set; }
        public Nullable<int> IDOrder { get; set; }
        public Nullable<int> IdStatusTracking { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
    
        public virtual Orders Orders { get; set; }
        public virtual StatusTracking StatusTracking { get; set; }
    }
}
