//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KornilovaVarvara420Shop.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderItems
    {
        public int IDOrderItems { get; set; }
        public Nullable<int> IDOrder { get; set; }
        public Nullable<int> IDProduct { get; set; }
        public Nullable<int> Quantity { get; set; }
    
        public virtual Orders Orders { get; set; }
        public virtual Produts Produts { get; set; }
    }
}
