//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KornilovaVarvara420Shop.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TopUps
    {
        public int IDTopUps { get; set; }
        public Nullable<int> IDUser { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<int> CardNumber { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
